### ISSUE TITLE
Remove optional run requirement on twisted

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/prometheus_client-feedstock#11]
`twisted` looks to be an [optional dependency](https://github.com/prometheus/client_python/blob/v0.3.1/setup.py#L20-L21) of `prometheus_client`.  Does it make sense to remove `twisted` from the list of run requirements for this recipe and allow users to choose to install twisted if they need the additional functionality?

One concern with the extra requirement is that Jupyter `notebook` as of version 5.6.0 has a dependency on `prometheus_client`, see conda-forge/notebook-feedstock#34.  Requiring `twisted` and its associated dependencies will add size to all environments containing `notebook`.

**Comment by rolweber** [comment]
Another option would be to introduce a `prometheus_client_base` or similar, on which `notebook` could depend. Like we have `tensorflow` and `tensorflow-base`, or `keras` and `keras-base`.

**Comment by rolweber** [comment]
Thanks!
